### ISSUE TITLE
Path to original file seems to be wrong when develop with windows

### ISSUE THREAD

**Issue by tloeffler** [dfeyer/flow-debugproxy#11]
My environment:

PhpStorm 10, Windows 8.1, local apache

The proxy runs fine and it breaks at the first line. When it comes into a controller the proxy writes this:

```
open /C:/Development/dev_php/flow_test/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Acme_Demo_Controller_StandardController.php: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
```

The break point in the controller is ignored.

It seems the proxy searches the original file under the wrong root (/C:...).
The cache file has the correct path appended.

I'm not familiar with Go so I cannot make a fix and a pull request.

Can you check this please?

**Comment by tloeffler** [comment]
I have a multiboot system now (Windows 8.1 / Linux) and can confirm the issue.
With Windows the original file is never found and no breakpoint from a cached equivalent is called.
With Linux all is fine.

So this is no problem anymore for me, but maybe you can fix this for windows developer.

**Comment by dfeyer** [comment]
@tloeffler Thanks for opening this issue, I don't have a working dev environnement on Windows actually but as soon as I setup one, I try to solve this issue.

**Comment by dlubitz** [comment]
@dfeyer Are you interested in supporting windows? I could provide a patch with the changes I did to get it run on windows. But it's not mergable, because it works only on windows now. But it could show up the affected positions in the code for further changes.

**Comment by dlubitz** [comment]
See: https://github.com/dlubitz/flow-debugproxy/commit/17b04889a2acf6b6c2a2d9137a87cb2ec3deef8d

**Comment by dfeyer** [comment]
@tloeffler Can you check https://github.com/dfeyer/flow-debugproxy/pull/21 and has you have access to a windows and linux system, can you confirm that everything work with the PR ?

@dlubitz Thanks for sharing your hack ... my version is just a conditional hack ;)

**Comment by fteuber** [comment]
For me, mapping in windows works (with localroot like "\\host\project\" and a Subcontext). Slashes in path when requesting the file seem to be no problem.

**Comment by dlubitz** [comment]
Looks good by reading for me. Thanks for taking care.

**Comment by dfeyer** [comment]
OK I will merge the change and release a new version, first version with Windows support, thanks for help

**Comment by tloeffler** [comment]
Sorry, I don't have a windows system anymore, using only Linux :(
