### ISSUE TITLE
flowpathmapper requires cache path to include "Data/Temporary" which can be omitted

### ISSUE THREAD

**Issue by vertexvaar** [dfeyer/flow-debugproxy#17]
Hi there,

i'm currently trying to use your great package in a docker environment and finally got it working.

One of the stumbling stone was that the path to the temporary files is expected to contain "Data/Temporary".
In fact, if the environment variable (rather php const) `FLOW_PATH_TEMPORARY_BASE` is defined it will be used as absolute path to the temporary files without having "Data/Temporary" appended.
In my case the provider of the Dockerfile set `FLOW_PATH_TEMPORARY_BASE=/opt/tmp` which resulted in the flow-debugproxy not finding any proxies.

Settings  `cachePathPattern` in [flowpathmapper.go#L26](https://github.com/dfeyer/flow-debugproxy/blob/master/flowpathmapper/flowpathmapper.go#L26) to `"@base@/@context@/Cache/Code/Flow_Object_Classes/@filename@.php"` should remedy this exact problem.

**Comment by dfeyer** [comment]
I think it's more complexe, the regex needs to be adapted too

**Comment by dfeyer** [comment]
The current workaround is to override the env var with something like this:

    FLOW_PATH_TEMPORARY_BASE=/opt/tmp/flow/Data/Temporary

**Comment by dfeyer** [comment]
I close this for now as the workaround is good enough and a clean solution is not easy
