### ISSUE TITLE
Please update docker image

### ISSUE THREAD

**Issue by vertexvaar** [dfeyer/flow-debugproxy#28]
Hi @dfeyer 

i've pulled the latest dfeyer/flow-debugproxy image from hub.docker.com but the binary version is still 1.0.1 whilst the most recent released version is 1.1.0. Could you please trigger a new docker image build? (Or make it run automatic ^^).
Thx

**Comment by dfeyer** [comment]
@vertexvaar Sorry i late this project without maintenance a bit too long

Automatic build of the docker image is configured and now we can build the project again
